;Unit DualKmeter
;UnitTest
[env:test_UnitDualKmeter_Core]
extends=Core, option_release, arduino_latest
lib_deps = ${Core.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_dual_kmeter

[env:test_UnitDualKmeter_Core2]
extends=Core2, option_release, arduino_latest
lib_deps = ${Core2.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_dual_kmeter

[env:test_UnitDualKmeter_CoreS3]
extends=CoreS3, option_release, arduino_latest
lib_deps = ${CoreS3.lib_deps} 
  ${test_fw.lib_deps}
test_filter= embedded/test_dual_kmeter

[env:test_UnitDualKmeter_Fire]
extends=Fire, option_release, arduino_latest
lib_deps = ${Fire.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_dual_kmeter

[env:test_UnitDualKmeter_Tab5]
extends=Tab5, option_release, pioarduino_latest
build_flags = ${Tab5.build_flags}
  ${option_release.build_flags}
lib_deps = ${Tab5.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_dual_kmeter

;Examples
[env:UnitDualKmeter_PlotToSerial_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitDualKmeter/PlotToSerial>

[env:UnitDualKmeter_PlotToSerial_Core2_Arduino_latest]
extends=Core2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitDualKmeter/PlotToSerial>

[env:UnitDualKmeter_PlotToSerial_CoreS3_Arduino_latest]
extends=CoreS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitDualKmeter/PlotToSerial>

[env:UnitDualKmeter_PlotToSerial_Fire_Arduino_latest]
extends=Fire, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitDualKmeter/PlotToSerial>

[env:UnitDualKmeter_PlotToSerial_Tab5_Arduino_latest]
extends=Tab5, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitDualKmeter/PlotToSerial>


; --------------------------------
;GraphicalMeter example
; --------------------------------
; For the following samples, please refer to PlotToSerial to create env for your own environment
; 以下のサンプルは、PlotToSerial を参考にして、自分の環境にあった env を作成してください
[env:UnitDualKmeter_GraphicalMeter_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_flags = ${option_release.build_flags}  -DUSING_UNIT_DUAL_KMETER
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/GraphicalMeter>

; [env:UnitDualKmeter_GraphicalMeter_Tab5_Arduino_latest]
; extends=Tab5, option_release, pioarduino_latest
; build_flags = ${Tab5.build_flags}
;   ${option_release.build_flags}
;   -DUSING_UNIT_DUAL_KMETER
; build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/GraphicalMeter>



